export const githubLink = "https://github.com/moates695";
export const finskaGithubLink = "https://github.com/moates695/finska";
export const balderdashGithubLink = "https://github.com/moates695/balderdash";
export const expoLink = "https://expo.dev/accounts/moates";
export const finskaExpoLink = "https://expo.dev/accounts/moates/projects/finska";
export const gymJunkiePlayStoreLink = "https://play.google.com/store/apps/details?id=au.com.moates.gymjunkie&hl=en";
export const gymJunkieAppStoreLink = "https://apps.apple.com/au/app/gym-junkie/id6769685454";
export const woodchuckPlayStoreLink = "https://play.google.com/store/apps/details?id=au.com.moates.woodchuck&hl=en";
export const pypiLink = "https://pypi.org/user/moates/";
export const downerhelperLink = "https://pypi.org/project/downerhelper/"
export const stravaLink = "https://www.strava.com/athletes/46665081"
export const cellularTrackingGithubLink = "https://github.com/moates695/cs9517_Group_Project"
export const postgresDeployLink = "https://pypi.org/project/postgresdeploy/"
export const imaxBotGithubLink = "https://github.com/moates695/imax_bot"
export const mcpServerGithubLink = "https://github.com/moates695/moates_mcp"
export const secretsVaultGithubLink = "https://github.com/moates695/secrets_vault"
export const mcpServerEndpoint = "https://mcp.moates.com.au/mcp"
export const paypalLink = "https://paypal.me/moates695";